// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {runGeneratorService} from '../models';

export function GenerateRun(arg1:runGeneratorService.RunOption):Promise<runGeneratorService.Run>;

export function GetActivityTypes():Promise<Array<runGeneratorService.ActivityType>>;

export function GetFractions():Promise<Array<runGeneratorService.Fraction>>;

export function SaveRun(arg1:runGeneratorService.Run):Promise<void>;
