// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GenerateRun(arg1) {
  return window['go']['main']['App']['GenerateRun'](arg1);
}

export function GetActivityTypes() {
  return window['go']['main']['App']['GetActivityTypes']();
}

export function SaveRun(arg1) {
  return window['go']['main']['App']['SaveRun'](arg1);
}
